name: Issue Forms Body Parser

on: issues

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: andyfeller/issueops-createrepo/parse@v1
      - run: echo ${{ toJSON(steps.parse.outputs.data) }}
